FROM python:3.7-buster

RUN apt update
RUN apt install -y portaudio19-dev libatlas-base-dev 

WORKDIR /bifrost 

COPY pycommons/libs pycommons/libs
COPY pycommons/resources pycommons/resources
COPY asr/libs/snowboy-1.3.0-py3.7-none-any.whl asr/libs/snowboy-1.3.0-py3.7-none-any.whl

COPY pycommons/requirements.txt pycommons/requirements.txt
COPY asr/requirements.txt asr/requirements.txt
RUN pip install -r pycommons/requirements.txt
RUN pip install -r asr/requirements.txt

COPY pycommons/audio pycommons/audio/
COPY pycommons/config pycommons/config/
COPY pycommons/asr.py pycommons/asr.py
COPY pycommons/mqtt.py pycommons/mqtt.py
COPY asr/asr asr/asr/

ENV PYTHONPATH=/bifrost
CMD [ "python", "asr/asr" ]
